version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: fullcycle-nginx
    ports:
      - "8888:80"
    depends_on:
      - node
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    build: ./node
    container_name: fullcycle-node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: fullcycle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
